### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by BohdanHarabadzhyu** [BohdanHarabadzhyu/homepage#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by TheMysteriousStranger90** [comment]
OK

**Comment by BohdanHarabadzhyu** [comment]
Thanks...

**Comment by BohdanHarabadzhyu** [comment]
...
